baseURL = "https://ankushchadda.in/"
languageCode = "en-us"
title = "Ankush Chadda"
theme = "hyde"
paginate = 5

# Enable syntax highlighting
pygmentsstyle = "vs"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

googleAnalytics = "UA-56883493-1"
disqusShortname = "ankushchaddablog"

[params]
	description = "Occassional Coder"
	copyright = "© Ankush Chadda. All rights reserved"

	# Content types to disable Disqus on.
	disableDisqusTypes = ["page"]

	themeColor = "theme-base-08"
	github = "https://github.com/iamkhush/"
	twitter = "http://twitter.com/iamkhush"
	linkedin = "https://www.linkedin.com/in/iamkhush/"
	email = "mailto:aoswebdevelopers@gmail.com"

# Nav.
[Menus]
main = [
	  {Name = "About me", URL = "/about"},
	  {Name = "All Posts", URL = "/posts"},
	  {Name = "Tags", URL = "/tags"},
	  {Name = "Feed", URL = "/index.xml"}
  ]

[taxonomies]
   tag = "tags"
