baseURL = "https://ankushchadda.in/"
languageCode = "en-us"
title = "Ankush Chadda"
theme = "hyde"
paginate = 5
copyright = "©"

# Enable syntax highlighting
pygmentsstyle = "vs"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

googleAnalytics = "UA-56883493-1"
disqusShortname = "Ankush Chadda's HomeSite"

[params]
	description = "Seeker; Wanderer; Occassional Coder"
	
	# Optional 64x64 avatar image.
	avatar = "/profile.png"

	disqus_shortname = 'ankushchaddablog'

	# Content types to disable Disqus on.
	disableDisqusTypes = ["page"]

	themeColor = "theme-base-08"
	github = "https://github.com/iamkhush/"
	twitter = "http://twitter.com/iamkhush"
	linkedin = "https://www.linkedin.com/in/iamkhush/"

# Nav.
[Menus]
main = [
	  {Name = "About", URL = "/about"},
	  {Name = "All Posts", URL = "/posts"}
  ]

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4


[[params.social]]
name = "RSS"
icon = "rss"
url = "/index.xml"

[taxonomies]
   tag = "tags"
