baseURL = "https://ankushchadda.in/"
languageCode = "en-us"
title = "Ankush Chadda"
theme = "hugo-ink"
paginate = 5

copyright = "© Copyright notice"

# Enable syntax highlighting
pygmentsstyle = "vs"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

googleAnalytics = "UA-56883493-1"
disqusShortname = "Ankush Chadda's HomeSite"

[params]
	subtitle = "Wanderer, Occassional Coder"

	# Optional 64x64 avatar image.
	avatar = "/profile.png"

	disqus_shortname = 'ankushchaddablog'

	# Content types to disable Disqus on.
	disableDisqusTypes = ["page"]
	
	featherIconsCDN = true

	mode = "auto" # "dark" or "auto"
	# customCSS = "css/custom.css"  # Custom CSS applied to default styles.
	# customDarkCSS = "css/custom-dark.css"  # Custom styles applied to dark mode css.
	# customJS = ["js/custom.js", "js/custom1.js"]  # Custom JS scripts.

# Nav.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/iamkhush"

[[params.social]]
name = "Facebook"
icon = "facebook"
url = "http://facebook.com/iamkhush"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "http://twitter.com/iamkhush"

[[params.social]]
name = "Linkedin"
icon = "linkedin"
url = "http://linkedin.com/in/iamkhush"

[[params.social]]
name = "RSS"
icon = "rss"
url = "/index.xml"

[taxonomies]
   tag = "tags"
